name: customer_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  video_player: ^2.11.1
  visibility_detector: ^0.4.0+2
  flutter_native_splash: ^2.4.4
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  image_picker: ^1.2.3
  shared_preferences: ^2.5.5
  intl: ^0.20.3
  firebase_core: ^4.12.1
  firebase_messaging: ^16.4.3
  url_launcher: ^6.3.2
  share_plus: ^13.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21   

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

# This MUST be at root level, NOT inside flutter:
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android_12:
    color: "#FFFFFF"
    image: assets/logo.png