// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Flip to `true` once you have registered a **Web** app in the Firebase
  /// console (Project settings -> Your apps -> Web) and pasted its values into
  /// [web] below, plus the Web Push certificate key pair into
  /// `PushService.webVapidKey`.
  ///
  /// While this is `false` the web build simply runs without Firebase: the
  /// notification bell, the notification list and every other API-backed
  /// feature still work, because those come from our own Django backend. Only
  /// browser push notifications are off.
  static const bool webConfigured = false;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      if (webConfigured) return web;
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'set DefaultFirebaseOptions.webConfigured to true after filling in '
        'the web options below.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcoOkAcAuvLZ9AlJzMn2BoGmgqihUk1-8',
    appId: '1:392326867102:android:5a8df5d6a203a28442f38f',
    messagingSenderId: '392326867102',
    projectId: 'rni-home-services',
    storageBucket: 'rni-home-services.firebasestorage.app',
  );

  // STILL THE OLD PROJECT. Android has moved to the client's Firebase project
  // (rni-home-services); iOS has not, because its GoogleService-Info.plist has
  // not been issued yet. Replace all six values from that file when it arrives.
  //
  // Nothing is broken by this today -- an iOS build needs a Mac, which is not
  // set up yet, so this path is unreachable. It is only dangerous the moment
  // someone does build for iPhone: push would silently register against a
  // Firebase project the client does not own, and no notification the backend
  // sends would ever arrive.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjplCQd9VkhksKszwsA3dsQQtt9MoK-64',
    appId: '1:879153194201:ios:48297e3afca3c9b1bbcac8',
    messagingSenderId: '879153194201',
    projectId: 'prohome-8f3c8',
    storageBucket: 'prohome-8f3c8.firebasestorage.app',
    iosBundleId: 'com.rniservices.customer',
  );

  /// Placeholder. Replace every value with the ones from your Firebase console
  /// Web app, then set [webConfigured] to `true`.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'PASTE_WEB_API_KEY',
    appId: 'PASTE_WEB_APP_ID',
    messagingSenderId: '879153194201',
    projectId: 'prohome-8f3c8',
    authDomain: 'prohome-8f3c8.firebaseapp.com',
    storageBucket: 'prohome-8f3c8.firebasestorage.app',
  );
}
