// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Flip to `true` once you have registered a **Web** app in the Firebase
  /// console (Project settings -> Your apps -> Web) and pasted its values into
  /// [web] below, plus the Web Push certificate key pair into
  /// `PushService.webVapidKey`.
  ///
  /// While this is `false` the web build simply runs without Firebase: the
  /// notification bell, the notification list and every other API-backed
  /// feature still work, because those come from our own Django backend. Only
  /// browser push notifications are off.
  static const bool webConfigured = false;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      if (webConfigured) return web;
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'set DefaultFirebaseOptions.webConfigured to true after filling in '
        'the web options below.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcoOkAcAuvLZ9AlJzMn2BoGmgqihUk1-8',
    appId: '1:392326867102:android:5a8df5d6a203a28442f38f',
    messagingSenderId: '392326867102',
    projectId: 'rni-home-services',
    storageBucket: 'rni-home-services.firebasestorage.app',
  );

  // These values, not ios/Runner/GoogleService-Info.plist, are what actually
  // configure Firebase here: main.dart calls initializeApp with
  // DefaultFirebaseOptions.currentPlatform. The plist sits alongside them for
  // the Firebase iOS SDK's own use and must still be added to the Runner
  // target in Xcode -- it is on disk but not yet referenced by the project,
  // which cannot be done from Windows. See ios/README-firebase.md.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyisgCYmXFDGVGkRFk-FphwJyMuIBTvLY',
    appId: '1:392326867102:ios:30818f2f0637bdcb42f38f',
    messagingSenderId: '392326867102',
    projectId: 'rni-home-services',
    storageBucket: 'rni-home-services.firebasestorage.app',
    iosBundleId: 'com.rniservices.customer',
  );

  /// Placeholder. Register a **Web** app in the Firebase console
  /// (rni-home-services), paste its two values below, and set [webConfigured]
  /// to `true`. Browser push additionally needs the Web Push certificate key
  /// pair in `PushService.webVapidKey`.
  ///
  /// The four non-placeholder values below already point at the client's
  /// project, so only the two marked PASTE_ need filling in.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'PASTE_WEB_API_KEY',
    appId: 'PASTE_WEB_APP_ID',
    messagingSenderId: '392326867102',
    projectId: 'rni-home-services',
    authDomain: 'rni-home-services.firebaseapp.com',
    storageBucket: 'rni-home-services.firebasestorage.app',
  );
}
